In [24]:
import numpy as np

# После импорта библиотеки демонстрируем массивы

In [25]:
nums_array = np.array([1, 2, 3, 5])
nums_array

array([1, 2, 3, 5])

In [26]:
zeros_array = np.zeros(5)
zeros_array

array([0., 0., 0., 0., 0.])

In [27]:
ones_array = np.ones(5)
ones_array

array([1., 1., 1., 1., 1.])

In [28]:
nums_arange = np.arange(5)
nums_arange

array([0, 1, 2, 3, 4])

# выводим форму (shape) и тип данных с помощью dtype

In [29]:
nums_arange.shape


(5,)

In [30]:
nums_arange.dtype

dtype('int64')

# получаем отдельный элемент и извлекаем подмассив с помощью среза

In [31]:
nums_arange[4]

np.int64(4)

In [32]:

nums_arange[3:10]

array([3, 4])

# поэлементо складываем и умноженаем массивы

In [33]:
a = np.array([1, 2])
b = np.array([3, 5])
a+b

array([4, 7])

In [34]:
a*b

array([ 3, 10])

# вычисляем среднюю величину (mean)

In [35]:
(a+b).mean()

np.float64(5.5)